### ISSUE TITLE
TokenUtils.java 文件中 javax.xml 依赖缺失

### ISSUE THREAD

**Issue by littlecurl** [xuexiangjys/XHttpApi#1]
import javax.xml.bind.DatatypeConverter;
上面这句需要下面这个依赖，在你的pom.xml中并未发现。
`        <dependency>
            <groupId>javax.xml.bind</groupId>
            <artifactId>jaxb-api</artifactId>
            <version>2.3.1</version>
        </dependency>
`

**Comment by xuexiangjys** [comment]
这个javax.xml.bind.DatatypeConverter;呢是引入的JDK，不需要额外的依赖...
![image](https://user-images.githubusercontent.com/15059629/76383502-0860e200-6397-11ea-9270-54ba6b26af8a.png)
